# Generated by Django 4.0.5 on 2022-07-04 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='uid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
